dist: bionic
os: linux
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - clang-format-8

# Always test things that aren't pushes (like PRs)
# or test master or test tagged releases on push (with versioning)
if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
    fast_finish: true

script:
  - find examples include tests \(  -name "*.cc" -o -name "*.h" \) -exec clang-format -i {} \;
  - git diff-index --cached --quiet HEAD
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - GTEST_COLOR=1 ctest --verbose
